http:
  routers:
    livebox:
      entryPoints:
        - https
      rule: "Host(`livebox.corsair.tf`)"
      service: livebox
      priority: 1
      middlewares:
        - security@file

  services:
    livebox:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "http://192.168.1.1:80"