# HTTP redirect to HTTPS for all hosts

[http.routers.https-only]
  entryPoints = [ "http" ]
  rule = "HostRegexp(`{host:.+}`)"
  middlewares = [ "https-redirect" ]
  service = "noop@internal"
  priority = 1

[http.middlewares.https-redirect.RedirectScheme]
  scheme = "https"
  permanent = true
