#  to Livebox

[http.routers.livebox]
  entryPoints = [ "https" ]
  rule = "Host(`livebox.corsaire.duckdns.org`)"
  service = "livebox"
  priority = 1
  [http.routers.livebox.tls]
    certResolver = "acme"

[http.services.livebox.loadBalancer]
  passHostHeader = false
  [[http.services.livebox.loadBalancer.servers]]
    url = "http://192.168.1.1:80"
