#  to Syncthing

[http.routers.sync]
  entryPoints = [ "https" ]
  rule = "Host(`sync.corsaire.duckdns.org`)"
  service = "sync"
  priority = 1
  [http.routers.sync.tls]
    certResolver = "acme"

[http.services.sync.loadBalancer]
  [[http.services.sync.loadBalancer.servers]]
    url = "http://192.168.1.42:8384"
