#  to TVHeadend

[http.routers.tv]
  entryPoints = [ "https" ]
  rule = "Host(`tv.corsaire.duckdns.org`)"
  service = "tv"
  priority = 1
  [http.routers.tv.tls]
    certResolver = "acme"

[http.services.tv.loadBalancer]
  [[http.services.tv.loadBalancer.servers]]
    url = "http://homelab:9981"
