[global]
 checkNewVersion = true
 sendAnonymousUsage = false

[log]
 level = "WARN"
 filePath = "/etc/traefik/logs/traefik.log"

[accessLog]
 filePath = "/etc/traefik/logs/access.log"

[serversTransport]
  insecureSkipVerify = true

[providers]
 [providers.docker]
   endpoint = "unix:///var/run/docker.sock"
   watch = true
   exposedByDefault = false
 [providers.file]
   directory = "/etc/traefik/statics"
   watch = true

[entryPoints]
 [entryPoints.http]
   address = ":80"
 [entryPoints.https]
   address = ":443"

[api]
 dashboard = true

[metrics]
 [metrics.prometheus]
   buckets = [0.1,0.3,1.2,5.0]

[certificatesResolvers]
 [certificatesResolvers.acme.acme]
   email = "macksize@gmail.com"
   storage = "/etc/traefik/acme/acme.json"
   [certificatesResolvers.acme.acme.httpChallenge]
     entryPoint = "http"
