name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    restart: unless-stopped
    stop_grace_period: 10s
    cpus: 3
    mem_limit: 2048m
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
      - no-new-privileges:true
    depends_on:
      - redis
      - database
    networks:
      - immich
      - traefik
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /mnt/tank/media/photos:/usr/src/app/upload/library
      - /mnt/tank/media/photos/Max:/library/Max:ro
      - /mnt/tank/media/photos/Sixtine:/library/Sixtine:ro
      - /mnt/tank/media/photos/JD:/library/JD:ro
      - /mnt/tank/media/photos/Stephanie:/library/Stephanie:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    healthcheck:
      disable: false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.photos.entrypoints=https"
      - "traefik.http.routers.photos.rule=Host(`photos.corsair.tf`)"
      - "traefik.http.routers.photos.middlewares=security@file"
      - "traefik.docker.network=traefik"

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      disable: false
    stop_grace_period: 5s
    cpus: 2
    mem_limit: 4096m
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
      - no-new-privileges:true
    networks:
      - immich

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped
    stop_grace_period: 5s
    cpus: 1
    mem_limit: 1024m
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
      - no-new-privileges:true
    networks:
      - immich

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    shm_size: 128mb
    restart: unless-stopped
    stop_grace_period: 5s
    cpus: 2
    mem_limit: 2048m
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
      - no-new-privileges:true
    networks:
      - immich

volumes:
  model-cache:

networks:
  immich:
    external: true
  traefik:
    external: true
