name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    restart: unless-stopped
    stop_grace_period: 10s
    cpus: 2
    mem_limit: 2048m
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
      - no-new-privileges:true
    command: [ 'start.sh', 'immich' ]
    depends_on:
      - redis
      - database
    networks:
      - immich
      - traefik
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /mnt/nas/media/Photos:/usr/src/app/upload/library
      - /mnt/nas/media/Photos/Max:/library/Max:ro
      - /mnt/nas/media/Photos/Sixtine:/library/Sixtine:ro
      - /mnt/nas/media/Photos/JD:/library/JD:ro
      - /mnt/nas/media/Photos/Stephanie:/library/Stephanie:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.photos.entrypoints=https"
      - "traefik.http.routers.photos.rule=Host(`photos.corsaire.duckdns.org`)"
      - "traefik.http.routers.photos.tls=true"
      - "traefik.http.routers.photos.tls.certresolver=acme"
      - "traefik.docker.network=traefik"

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ 'start.sh', 'microservices' ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /mnt/nas/media/Photos:/usr/src/app/upload/library
      - /mnt/nas/media/Photos/Max:/library/Max:ro
      - /mnt/nas/media/Photos/Sixtine:/library/Sixtine:ro
      - /mnt/nas/media/Photos/JD:/library/JD:ro
      - /mnt/nas/media/Photos/Stephanie:/library/Stephanie:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: unless-stopped
    stop_grace_period: 5s
    cpus: 2
    mem_limit: 2048m
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
      - no-new-privileges:true
    networks:
      - immich

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /mnt/nas/media/Photos:/usr/src/app/upload/library
      - /mnt/nas/media/Photos/Max:/library/Max:ro
      - /mnt/nas/media/Photos/Sixtine:/library/Sixtine:ro
      - /mnt/nas/media/Photos/JD:/library/JD:ro
      - /mnt/nas/media/Photos/Stephanie:/library/Stephanie:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    restart: unless-stopped
    stop_grace_period: 5s
    cpus: 1
    mem_limit: 1024m
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
      - no-new-privileges:true
    networks:
      - immich

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped
    stop_grace_period: 5s
    cpus: 1
    mem_limit: 1024m
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
      - no-new-privileges:true
    networks:
      - immich

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    restart: unless-stopped
    stop_grace_period: 5s
    cpus: 2
    mem_limit: 2048m
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
      - no-new-privileges:true
    command:
      [
        "postgres",
        "-c",
        "shared_preload_libraries=vectors.so",
        "-c",
        'search_path="$$user", public, vectors',
        "-c",
        "logging_collector=on",
        "-c",
        "max_wal_size=2GB",
        "-c",
        "shared_buffers=512MB",
        "-c",
        "wal_compression=on"
      ]

    networks:
      - immich

volumes:
  model-cache:


networks:
  immich:
    external: true
  traefik:
    external: true
