name: docs
services:
  affine:
    container_name: affine_server
    image: ghcr.io/toeverything/affine:${AFFINE_REVISION:-stable}
    restart: unless-stopped
    cpus: 3
    mem_limit: 2048m
    security_opt:
      - no-new-privileges:true
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      affine_migration:
        condition: service_completed_successfully
    volumes:
      # custom configurations
      - ${UPLOAD_LOCATION}:/root/.affine/storage
      - ${CONFIG_LOCATION}:/root/.affine/config
    env_file:
      - .env
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE:-affine}
      - AFFINE_INDEXER_ENABLED=false
    networks:
      - affine
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docs2.entrypoints=https"
      - "traefik.http.routers.docs2.rule=Host(`docs2.corsair.tf`)"
      - "traefik.http.routers.doc2.middlewares=security@file"
      - "traefik.http.routers.docs2.service=docs2"
      - "traefik.http.services.docs2.loadbalancer.server.port=3010"
      - "traefik.docker.network=traefik"

  affine_migration:
    image: ghcr.io/toeverything/affine:${AFFINE_REVISION:-stable}
    container_name: affine_migration_job
    volumes:
      # custom configurations
      - ${UPLOAD_LOCATION}:/root/.affine/storage
      - ${CONFIG_LOCATION}:/root/.affine/config
    command: ["sh", "-c", "node ./scripts/self-host-predeploy.js"]
    env_file:
      - .env
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE}
      - AFFINE_INDEXER_ENABLED=false
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - affine

  redis:
    image: redis
    container_name: affine_redis
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - affine

  postgres:
    image: pgvector/pgvector:pg16
    container_name: affine_postgres
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_INITDB_ARGS: "--data-checksums"
      # you better set a password for you database
      # or you may add 'POSTGRES_HOST_AUTH_METHOD=trust' to ignore postgres security policy
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "${DB_USERNAME}", "-d", "${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - affine

  bentopdf:
    image: ghcr.io/alam00000/bentopdf-simple:latest
    container_name: bentopdf
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bentopdf.entrypoints=https"
      - "traefik.http.routers.bentopdf.rule=Host(`pdf.corsair.tf`)"
      - "traefik.http.routers.bentopdf.middlewares=security@file,auth@docker"
      - "traefik.http.routers.bentopdf.service=bentopdf"
      - "traefik.http.services.bentopdf.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik"

  papra:
    container_name: papra
    image: ghcr.io/papra-hq/papra:latest
    restart: unless-stopped
    volumes:
      - ./papra:/app/app-data
    user: "3000:3000"
    networks:
      - traefik
    env_file:
      - papra.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.papra.entrypoints=https"
      - "traefik.http.routers.papra.rule=Host(`archive.corsair.tf`)"
      - "traefik.http.routers.papra.middlewares=security@file,private@file"
      - "traefik.http.routers.papra.service=papra"
      - "traefik.http.services.papra.loadbalancer.server.port=1221"
      - "traefik.docker.network=traefik"

  bookstack:
    container_name: bookstack
    image: lscr.io/linuxserver/bookstack:latest
    restart: unless-stopped
    depends_on:
      bookstack-db:
        condition: service_healthy
    env_file:
      - bookstack.env
    environment:
      - PUID=3000
      - PGID=3002
      - TZ=Europe/Paris
      - APP_URL=https://docs.corsair.tf
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_DATABASE=bookstack
      - AUTH_METHOD=oidc
      - AUTH_AUTO_INITIATE=true
      - OIDC_NAME=CorsairAuth
      - OIDC_DISPLAY_NAME_CLAIMS=name
      - OIDC_ISSUER=https://login.corsair.tf
      - OIDC_ISSUER_DISCOVER=true
      - OIDC_END_SESSION_ENDPOINT=true
    volumes:
      - ./bookstack:/config
    networks:
      - bookstack
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bookstack.entrypoints=https"
      - "traefik.http.routers.bookstack.rule=Host(`docs.corsair.tf`)"
      - "traefik.http.routers.bookstack.middlewares=security@file"
      - "traefik.http.routers.bookstack.service=bookstack"
      - "traefik.http.services.bookstack.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"

  bookstack-db:
    container_name: bookstack_db
    image: lscr.io/linuxserver/mariadb:latest
    restart: unless-stopped
    env_file:
      - bookstack.env
    environment:
      - PUID=3000
      - PGID=3002
      - TZ=Europe/Paris
      - MYSQL_DATABASE=bookstack
    volumes:
      - /mnt/fast/dbs/homelab/bookstack:/config
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-uroot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - bookstack

networks:
  affine:
    external: true
  bookstack:
    external: true
  traefik:
    external: true
