appConfig:
    webSearch:
        searchEngine: duckduckgo
        openingMethod: newtab
        searchBangs:
            gg: https://www.google.com/search?q=
            yt: https://www.youtube.com/results?search_query=
            maps: https://www.google.fr/maps/search/
            wiki: https://en.wikipedia.org/w/?search=
            trans: https://translate.google.com/?sl=en&tl=fr&text=
    faviconApi: iconhorse
    auth:
        users:
            - user: ENC[AES256_GCM,data:h1Xt,iv:Ccal0xKveWNF967bAP4tRYSVe29ONcOs+L3MGMoPRqc=,tag:M/mJkD/MUWwIQ+b22CvXdg==,type:str]
              hash: ENC[AES256_GCM,data:pAQU0X9jpeTh0BFPsSOYWKDf3UNCzWcRU49LrIVX71HSiP895S1KMWB94EMg6BSJHyWd/6pHhOeagJ346Qe0MA==,iv:5POnMfJNDXSJsyWg/kOwaXzvPUh9dwuR0vxRk7oKjeA=,tag:tEMljezVHIWp2ju07LwnVQ==,type:str]
              type: ENC[AES256_GCM,data:mYT3Xa4=,iv:U4sXr8pHm07TP7t5+rVeR/7kC6TeLS64v36FEJbwLcY=,tag:aZVjsUf2q1S6ExsOLbptQQ==,type:str]
        enableGuestAccess: true
    iconSize: small
    theme: nord-custom
    cssThemes:
        - nord-custom
    hideComponents:
        hideSettings: true
    routingMode: history
    disableConfigurationForNonAdmin: true
    layout: auto
pages:
    - name: Hobbies
      path: hobbies.yml
    - name: Work
      path: work.yml
    - name: Health
      path: health.yml
pageInfo:
    title: Corsaire Labs
    description: Dashboard
    logo: /img/corsaire.png
    footerText: <a data-v-001d966c="" href="https://github.com/maxpoullain/homelab" target="_blank">Corsaire Labs source code</a>
sections:
    - name: Today's sea
      icon: fas fa-windsock
      displayData:
        rows: 2
      widgets:
        - type: clock
          options:
            timeZone: Europe/Paris
            format: fr-FR
            hideSeconds: true
            customCityName: Saint-Malo
          id: 0_1012_clock
        - type: weather
          options:
            apiKey: ENC[AES256_GCM,data:FWdFr/7S7Q3Hql+PX7Eblf+KLbPUMiWXsS4pg6b6BT4=,iv:f44FF36XXhVExOGymS4ivpa7TotaU2nSoXo3Zx9UHr4=,tag:cy6dSa124BEW+SSr41AFtw==,type:str]
            city: St-Malo
            units: metric
          id: 1_1012_weather
        - type: weather-forecast
          options:
            city: St-Malo
            znumDays: 6
            apiKey: ENC[AES256_GCM,data:SA3wRAku6DDPef8N6SZqhIAow/Mx11kdOdDJI7VACWo=,iv:w/CQHQVwkH26Eo6wd8ovM5rYyIjUrgv0eAzr2OQXgfI=,tag:2zLWqTyvuydryMqpCP8JXA==,type:str]
            units: metric
          id: 2_1012_weatherforecast
    - name: Shanties
      icon: fas fa-music
      displayData:
        rows: 1
      items:
        - title: Twitch
          icon: twitch.png
          description: Games streaming service
          url: https://www.twitch.tv/directory/following
          id: 0_831_twitch
        - title: Youtube
          icon: youtube.png
          description: Enjoy the videos and music you love
          url: https://www.youtube.com/feed/subscriptions
          id: 1_831_youtube
        - title: Jellyfin
          icon: jellyfin.png
          description: Free software media system
          url: https://tv.corsaire.duckdns.org/
          statusCheck: true
          id: 2_831_jellyfin
        - title: Immich
          icon: immich.png
          description: High performance self-hosted photo and video management solution
          url: https://photos.corsaire.duckdns.org/
          statusCheck: true
          id: 3_831_immich
        - title: Prime Video
          icon: primevideo.png
          description: Streaming video service
          url: https://www.primevideo.com/
          id: 4_831_primevideo
        - title: Netflix
          icon: netflix.png
          description: Streaming video service
          url: https://www.netflix.com/
          id: 5_831_netflix
        - title: F1 TV
          icon: f1tv.png
          description: Enter the world of Formula 1
          url: https://f1tv.formula1.com/
          id: 6_831_ftv
    - name: Booty
      icon: fas fa-coins
      displayData:
        rows: 1
      items:
        - title: Finary
          icon: finary.png
          description: The ultimate portfolio tracker
          url: https://app.finary.com/v2
          id: 0_525_finary
        - title: BoursoBank
          icon: brs.png
          description: Banking service
          url: https://clients.boursorama.com/connexion/
          id: 1_525_boursobank
        - title: CA
          icon: ca.png
          description: Banking service
          url: https://www.credit-agricole.fr/ca-normandie/particulier/acceder-a-mes-comptes.html
          id: 2_525_ca
        - title: Degiro
          icon: degiro.png
          description: Stock broker
          url: https://www.degiro.fr/
          id: 3_525_degiro
        - title: Wise
          icon: wise.png
          description: Send money abroad
          url: https://wise.com/
          id: 4_525_wise
    - name: Your ship
      icon: fas fa-ship
      displayData:
        rows: 1
      widgets:
        - type: public-ip
          id: 0_899_publicip
    - name: Docks
      icon: fas fa-anchor
      displayData:
        rows: 1
      items:
        - title: Notion
          icon: notion.png
          description: Productivity and note-taking app
          url: https://www.notion.so/
          id: 0_500_notion
        - title: Reddit
          icon: reddit.png
          description: Network of communities
          url: https://reddit.com/
          id: 1_500_reddit
        - title: Github
          icon: github.png
          description: Code hosting platform
          url: https://github.com/
          id: 2_500_github
        - title: Amazon
          icon: amazon.png
          description: E-commerce site
          url: https://www.amazon.fr/
          id: 3_500_amazon
        - title: Meteo France
          icon: favicon
          description: French national meteorological service
          url: https://meteofrance.com/previsions-meteo-france/saint-malo/35400
          id: 4_500_meteofrance
        - title: LinkedIn
          icon: linkedin.png
          description: Professional networking
          url: https://www.linkedin.com/
          id: 5_500_linkedin
        - title: Facebook
          icon: facebook.png
          description: Connect with friends
          url: https://www.facebook.com/
          id: 6_500_facebook
    - name: Captain's Quarters
      icon: fas fa-dharmachakra
      displayData:
        rows: 2
      items:
        - title: HA
          icon: homeassistant.png
          description: Open-source software for home automation
          url: https://home.corsaire.duckdns.org/
          statusCheck: true
          id: 0_1745_ha
        - title: NAS
          icon: nas.png
          description: QNAP
          url: https://nas.corsaire.duckdns.org/cgi-bin/
          statusCheck: true
          id: 1_1745_nas
        - title: Traefik
          icon: traefik.png
          description: Modern reverse proxy
          url: https://traefik.corsaire.duckdns.org/
          statusCheck: true
          statusCheckAcceptCodes: "401"
          id: 2_1745_traefik
        - title: Glances
          icon: glances.png
          description: Cross-platform system monitoring tool written in Python
          url: https://health.corsaire.duckdns.org/
          statusCheck: true
          statusCheckAcceptCodes: "401"
          id: 3_1745_glances
        - title: WAN
          icon: wan.png
          description: ISP router
          url: https://livebox.corsaire.duckdns.org/
          statusCheck: true
          id: 4_1745_wan
        - title: Transmission
          icon: transmission.png
          description: BitTorrent client
          url: https://seedbox.corsaire.duckdns.org/
          statusCheck: true
          statusCheckAcceptCodes: "401"
          id: 5_1745_transmission
        - title: Sonarr
          icon: sonarr.png
          description: TV show collection manager
          url: https://shows.corsaire.duckdns.org/
          statusCheck: true
          id: 6_1745_sonarr
        - title: Radarr
          icon: radarr.png
          description: Movie collection manager
          url: https://movies.corsaire.duckdns.org/
          statusCheck: true
          id: 7_1745_radarr
        - title: Readarr
          icon: readarr.png
          description: Books collection manager
          url: https://books.corsaire.duckdns.org/
          statusCheck: true
          id: 8_1745_readarr
        - title: Prowlarr
          icon: prowlarr.png
          description: Arr indexer manager/proxy
          url: https://prowlarr.corsaire.duckdns.org/
          statusCheck: true
          id: 9_1745_prowlarr
        - title: PIA
          description: PIA VPN protects your digital identity by rerouting your internet traffic through private and secure servers.
          icon: pia.png
          url: https://https://www.privateinternetaccess.com/account/client-control-panel#subscription-overview/
          id: 10_1745_pia
        - title: Backblaze
          icon: backblaze.png
          description: Robust, scalable low cost cloud backup and storage services
          url: https://backblaze.com/
          id: 11_1745_backblaze
        - title: KeeWeb
          icon: keeweb.png
          description: Cross-platform password manager
          url: https://app.keeweb.info/
          id: 12_1745_keeweb
    - name: The 7 seas
      icon: fas fa-skull-crossbones
      displayData:
        rows: 3
      widgets:
        - type: rss-feed
          options:
            rssUrl: https://www.france24.com/fr/rss
            limit: 6
            orderDirection: asc
          id: 0_836_rssfeed
        - type: public-holidays
          options:
            country: fr
            holidayType: all
            monthsToShow: 4
            lang: fr
          id: 1_836_publicholidays
    - name: Catch of the day
      icon: fas fa-fish
      displayData:
        rows: 1
      widgets:
        - type: joke
          options:
            safeMode: true
          id: 0_1431_joke
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146kmjfn0h64zzchtp908lx7ln8mg8agt0ree7yurvev34veaqp5s0j9kaw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVGlhQzFhYVNKVXU5SUZG
            N0J3MWFaOXN1SCtpTmpkbkwwMG5iWFNuRFg0Clgxa1R1QWdwL0RzTU5RTVdIR1lK
            RzV2Y0ZlVi9RQVRvaHpkSHBQb1NrdjgKLS0tIEVWTzY5WkM1VnlRU1RqVTZSN0pE
            Ris1MFF1L2xvc1JvYmphOHFCeVNHLzAKxMB882Y0M52pGtQEw1lhn7ESgYukCSxT
            q1sy+hXGwcn+qsEomiS3fSoad5JHYLKOvW1wSVk9mY/BJC7avpZWTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T15:48:52Z"
    mac: ENC[AES256_GCM,data:LKbdtP+pu8UARIMkVRDdyM+ehpUjJhiuwy/MaOL6MswFmamRSNwSfD4lGWyNErIMMTdqw7lAFPUlVquUglOgoDeyipYwtq9F8mV1/z+IjS61yRUZtpta/ybRFDtrblL5Oky4SYVDrbnJbUPnpnW/Q7y/GHAPdbQ6xbS7NzpIJec=,iv:hh8lE1MlqwQ1o+CqXo7bOGE0Ke/60e9srNSNppeJ/OE=,tag:ef0EppClE6qLObRt5Vm4Mw==,type:str]
    pgp: []
    encrypted_regex: ^(.*hash.*|.*apiKey.*|.*password.*|.*DB_PASSWORD.*|.*USER.*|.*PASS.*|.*users.*|.*TOKEN.*|.*DNS.*|.*POST_UP.*|.*PRE_DOWN.*)$
    version: 3.9.1
