appConfig:
    webSearch:
        searchEngine: duckduckgo
        openingMethod: newtab
        searchBangs:
            gg: https://www.google.com/search?q=
            yt: https://www.youtube.com/results?search_query=
            maps: https://www.google.fr/maps/search/
            wiki: https://en.wikipedia.org/w/?search=
            trans: https://translate.google.com/?sl=en&tl=fr&text=
    faviconApi: iconhorse
    auth:
        users:
            - user: ENC[AES256_GCM,data:E2Mn,iv:wp3h+kGXSMzMWsNUbui23JEcb9aJzI3F7tFHOAwlRQU=,tag:tyoCl68qW2O7QgyAPadatQ==,type:str]
              hash: ENC[AES256_GCM,data:4sBZgIIUbYS/My0uh87dMEqvSANjz5Hqc+VopohR60h4HS9ZgrY9rorlP2thH0cGLII0QzKCbfzgHcXiGNlBuQ==,iv:2nxIetuh+ykU8BRDYtgbJTWk5/M5DCcEL92VTcx0Jh4=,tag:JvvlUfO8euoFq7a9OBGuPQ==,type:str]
              type: ENC[AES256_GCM,data:Jba3tHg=,iv:r4M4kp2grWgrQheD9NHv955nVJ2gQim7hYZDlY7qras=,tag:tgW7K7t/PELaYqs8b8HG7w==,type:str]
        enableGuestAccess: true
    iconSize: small
    theme: nord-custom
    cssThemes:
        - nord-custom
    hideComponents:
        hideSettings: true
    routingMode: history
    disableConfigurationForNonAdmin: true
pages:
    - name: Hobbies
      path: hobbies.yml
    - name: Work
      path: work.yml
    - name: Health
      path: health.yml
pageInfo:
    title: Corsaire Labs
    description: Dashboard
    logo: /img/corsaire.png
    footerText: <a data-v-001d966c="" href="https://github.com/maxpoullain/homelab" target="_blank">Corsaire Labs source code</a>
sections:
    - name: Today's sea
      icon: fas fa-windsock
      displayData:
        rows: 2
      widgets:
        - type: clock
          options:
            timeZone: Europe/Paris
            format: fr-FR
            hideSeconds: true
            customCityName: Saint-Malo
        - type: weather
          options:
            apiKey: ENC[AES256_GCM,data:X89tjedXMcLkovfpAemZyV9AHoW+yOlUDDFjLqfwyUo=,iv:RD7Qq8kcWcCtTgH1fxSC1Yo990GcmaUN2rhy8hw0Swc=,tag:ru3VO79H9N2Lafwq99ddTw==,type:str]
            city: St-Malo
            units: metric
        - type: weather-forecast
          options:
            city: St-Malo
            znumDays: 6
            apiKey: ENC[AES256_GCM,data:tl4NLMP45+ULK5B3fSUHQi/ZaQBEH+GYDYyYGn8ZwWc=,iv:qNig1RHFRVni9aXHsKaoVEToAfojDmamVQsT1aXz/9k=,tag:w6EL3B3LN0xXSZL7I2OBdw==,type:str]
            units: metric
    - name: Shanties
      icon: fas fa-music
      displayData:
        rows: 1
      items:
        - title: Twitch
          icon: twitch.png
          description: Games streaming service
          url: https://www.twitch.tv/directory/following
        - title: Youtube
          icon: youtube.png
          description: Enjoy the videos and music you love
          url: https://www.youtube.com/feed/subscriptions
        - title: Jellyfin
          icon: jellyfin.png
          description: Free software media system
          url: https://tv.corsaire.duckdns.org/
          statusCheck: true
        - title: Immich
          icon: immich.png
          description: High performance self-hosted photo and video management solution
          url: https://photos.corsaire.duckdns.org/
          statusCheck: true
        - title: Prime Video
          icon: primevideo.png
          description: Streaming video service
          url: https://www.primevideo.com/
        - title: Netflix
          icon: netflix.png
          description: Streaming video service
          url: https://www.netflix.com/
        - title: F1 TV
          icon: f1tv.png
          description: Enter the world of Formula 1
          url: https://f1tv.formula1.com/
    - name: Booty
      icon: fas fa-coins
      displayData:
        rows: 1
      items:
        - title: Finary
          icon: finary.png
          description: The ultimate portfolio tracker
          url: https://app.finary.com/v2
        - title: BoursoBank
          icon: brs.png
          description: Banking service
          url: https://clients.boursorama.com/connexion/
        - title: CA
          icon: ca.png
          description: Banking service
          url: https://www.credit-agricole.fr/ca-normandie/particulier/acceder-a-mes-comptes.html
        - title: Degiro
          icon: degiro.png
          description: Stock broker
          url: https://www.degiro.fr/
        - title: Wise
          icon: wise.png
          description: Send money abroad
          url: https://wise.com/
    - name: Your ship
      icon: fas fa-ship
      displayData:
        rows: 1
      widgets:
        - type: public-ip
    - name: Docks
      icon: fas fa-anchor
      displayData:
        rows: 1
      items:
        - title: Notion
          icon: notion.png
          description: Productivity and note-taking app
          url: https://www.notion.so/
        - title: Reddit
          icon: reddit.png
          description: Network of communities
          url: https://reddit.com/
        - title: Github
          icon: github.png
          description: Code hosting platform
          url: https://github.com/
        - title: Amazon
          icon: amazon.png
          description: E-commerce site
          url: https://www.amazon.fr/
        - title: Meteo France
          icon: favicon
          description: French national meteorological service
          url: https://meteofrance.com/previsions-meteo-france/saint-malo/35400
        - title: LinkedIn
          icon: linkedin.png
          description: Professional networking
          url: https://www.linkedin.com/
        - title: Facebook
          icon: facebook.png
          description: Connect with friends
          url: https://www.facebook.com/
    - name: Captain's Quarters
      icon: fas fa-dharmachakra
      displayData:
        rows: 2
      items:
        - title: HA
          icon: homeassistant.png
          description: Open-source software for home automation
          url: https://home.corsaire.duckdns.org/
          statusCheck: true
        - title: NAS
          icon: nas.png
          description: QNAP
          url: https://nas.corsaire.duckdns.org/cgi-bin/
          statusCheck: true
        - title: Traefik
          icon: traefik.png
          description: Modern reverse proxy
          url: https://traefik.corsaire.duckdns.org/
          statusCheck: true
          statusCheckAcceptCodes: "401"
        - title: Glances
          icon: glances.png
          description: Cross-platform system monitoring tool written in Python
          url: https://health.corsaire.duckdns.org/
          statusCheck: true
          statusCheckAcceptCodes: "401"
        - title: WAN
          icon: wan.png
          description: ISP router
          url: https://livebox.corsaire.duckdns.org/
          statusCheck: true
        - title: Transmission
          icon: transmission.png
          description: BitTorrent client
          url: https://seedbox.corsaire.duckdns.org/
          statusCheck: true
          statusCheckAcceptCodes: "401"
        - title: Sonarr
          icon: sonarr.png
          description: TV show collection manager
          url: https://shows.corsaire.duckdns.org/
          statusCheck: true
        - title: Radarr
          icon: radarr.png
          description: Movie collection manager
          url: https://movies.corsaire.duckdns.org/
          statusCheck: true
        - title: Readarr
          icon: readarr.png
          description: Books collection manager
          url: https://books.corsaire.duckdns.org/
          statusCheck: true
        - title: Prowlarr
          icon: prowlarr.png
          description: Arr indexer manager/proxy
          url: https://prowlarr.corsaire.duckdns.org/
          statusCheck: true
        - title: AirVPN
          icon: favicon
          description: OpenVPN and WireGuard based VPN operated by activists in defense of net neutrality, privacy and against censorship.
          url: https://airvpn.org/
        - title: Backblaze
          icon: favicon
          description: Robust, scalable low cost cloud backup and storage services
          url: https://backblaze.com/
        - title: KeeWeb
          icon: keeweb.png
          description: Cross-platform password manager
          url: https://app.keeweb.info/
    - name: The 7 seas
      icon: fas fa-skull-crossbones
      displayData:
        rows: 3
      widgets:
        - type: rss-feed
          options:
            rssUrl: https://www.france24.com/fr/rss
            limit: 6
            orderDirection: asc
        - type: public-holidays
          options:
            country: fr
            holidayType: all
            monthsToShow: 4
            lang: fr
    - name: Catch of the day
      icon: fas fa-fish
      displayData:
        rows: 1
      widgets:
        - type: joke
          options:
            safeMode: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146kmjfn0h64zzchtp908lx7ln8mg8agt0ree7yurvev34veaqp5s0j9kaw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjeGlEVzFzbEJjTnRQcnM4
            bFl5NHJtVUFtVVVwSkhFY2Zpb25vOUxHZ1E4CkFTL3BYcWNzV3h3U0N4cDVsZ3hZ
            RmhYdDQ1MzUyRVFVcEhwYyt0ejluQlEKLS0tIDN5OTcwWDFPdC9veGxkekEwR0ZH
            WkQ3WTRBN0JvbzZiQ0t5VHRVMzNqRncKGXCQOEbjv2bUtBrLPGdLeskanwojsTdS
            o5ngr2xZ2fRVsnk0aARcOdFFBNgyIaB112iKy3vtKqEPGNVkTvGFjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T12:17:02Z"
    mac: ENC[AES256_GCM,data:L9KiP9BJremim4Pk+SEoQJW1i5raCoL7w5PzVPSjXOYfa9/tSSCR+acI8o26tUIaNWJCJudFuZdMD1QGXXgf90JvIzmAK6sMemwAt/+6kb5S+bMpCZU2jYCcGqHT1HU5C7JuCEQaFt14QzQT5XAmUMUvOnl4KM3pdgAEFhV+gDo=,iv:7u2BNxXknp0GDTunSZ+ZnvSuJJ6SaBnDJx90sSwYnqQ=,tag:EW6uThjMSsshf6Xlmj0+8g==,type:str]
    pgp: []
    encrypted_regex: ^(.*hash.*|.*apiKey.*|.*password.*|.*DB_PASSWORD.*|.*USER.*|.*PASS.*|.*users.*|.*TOKEN.*|.*DNS.*|.*POST_UP.*|.*PRE_DOWN.*)$
    version: 3.9.1
