pageInfo:
    title: Corsaire Labs
    description: Health
    logo: /img/corsaire.png
    footerText: <a data-v-001d966c="" href="https://github.com/maxpoullain/homelab" target="_blank">Corsaire Labs source code</a>
sections:
    - name: Restricted access
      icon: fas fa-ban
      displayData:
        showForUsers:
            - noone
      items:
        - title: Login
          icon: fas fa-user
          description: Please login
          url: https://www.corsaire.duckdns.org/login
          target: sametab
    - name: System Alerts
      icon: fas fa-sensor-alert
      displayData:
        hideForGuests: true
        cols: 2
      widgets:
        - type: gl-alerts
          options:
            hostname: https://health.corsaire.duckdns.org
            username: max
            password: ENC[AES256_GCM,data:qvCr4hJPWA9L8g==,iv:uVNxMleHK6rgafKcBdL/WnZBEJ1jM6QXr+dDj4fzRPs=,tag:ITr2Jh4o1hhIBdZP0vb+sQ==,type:str]
    - name: Client IP
      icon: fas fa-desktop
      displayData:
        hideForGuests: true
      widgets:
        - type: public-ip
    - name: IP Addresses
      icon: fas fa-globe
      displayData:
        hideForGuests: true
      widgets:
        - type: gl-ip-address
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: max
                password: ENC[AES256_GCM,data:YV3EaVoulDLiew==,iv:NxWK5T1yYUBydQdncfPiYUyT+7Ws8gjldyGwAvJGh28=,tag:hYhiJ8Gn35LeOv4QFJ569w==,type:str]
    - name: CPU Usage
      icon: fas fa-tachometer
      displayData:
        hideForGuests: true
        rows: 2
      widgets:
        - type: gl-current-cpu
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: max
                password: ENC[AES256_GCM,data:uOlaS3SIcysbvQ==,iv:qDLFn8nOZABET1OkgIKErcDc8QHzH8EuN/CIUJyAWuk=,tag:OqS/jI8b7ou7MT6qHMX88w==,type:str]
        - type: gl-cpu-temp
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: max
                password: ENC[AES256_GCM,data:gn9zR2ewEC7HUw==,iv:mJY+W82ItFis1IMMQ2kpE5GN4ULuaXrRWubgvtvbL/o=,tag:lm3BoZXpxSquxsw3mBqNCA==,type:str]
          units: C
        - type: gl-current-cores
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: max
                password: ENC[AES256_GCM,data:GbGo/u2zZx9JhQ==,iv:eE9h+ev9mKtNRQ1X04cnap6N6IXzE+kY0moMuHw1Up8=,tag:ryovJ+X7G06tG22VkCbfxA==,type:str]
    - name: CPU History
      icon: fas fa-microchip
      displayData:
        hideForGuests: true
        cols: 2
      widgets:
        - type: gl-cpu-history
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: max
                password: ENC[AES256_GCM,data:HXg1Gf4smo6KuQ==,iv:mLcRCoElEM5e7med0E1kRO6E6cK6iwDWPALWgYmC/94=,tag:YXYjUlGDMpKWzAPR+4+HgQ==,type:str]
            limit: 60
    - name: Disk Space
      icon: fas fa-hdd
      displayData:
        hideForGuests: true
      widgets:
        - type: gl-disk-space
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: max
                password: ENC[AES256_GCM,data:I9R4H03kaiGZJQ==,iv:4rHzjmDgcY/qiaO+ls58Z9eQuzw4cEXT9aTRYBn87os=,tag:z2GXsfdiRCRxvhosmVp90w==,type:str]
    - name: Memory Usage
      icon: fas fa-memory
      displayData:
        hideForGuests: true
      widgets:
        - type: gl-current-mem
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: max
                password: ENC[AES256_GCM,data:gn98TKGnkHvNvA==,iv:sx9+jG0F6rV97uwlBvlK+mNx0HYrOu8Ql4E/wIVBio8=,tag:5Clyz0ScaBWR9GeQnNJeSg==,type:str]
    - name: System Load
      icon: fas fa-tasks-alt
      displayData:
        hideForGuests: true
      widgets:
        - type: gl-system-load
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: max
                password: ENC[AES256_GCM,data:1KebGNGE6kM00w==,iv:WCrgehHZRLEAPis1TaE1vkUVRcXFyFidzfhkLk7zNos=,tag:QBI3nQV/g/GkRKik3+QR7A==,type:str]
    - name: Disk IO
      icon: fas fa-disc-drive
      displayData:
        hideForGuests: true
      widgets:
        - type: gl-disk-io
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: max
                password: ENC[AES256_GCM,data:c6/7MGpKhko/xg==,iv:6aNlwt7YMpvBVjkRzdErG+oocHHBiqkC+drQjmH2cR8=,tag:TjCSBOKNEOKjYWFtE3OveA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146kmjfn0h64zzchtp908lx7ln8mg8agt0ree7yurvev34veaqp5s0j9kaw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcGtNdkpmbjNsa2xsNzUz
            NTh5N3RwaThLT0FLQnNaQXIxcjBlYllTMEJBCmNsVWY1cXo3OTYweW4vY0FncDJU
            Unlnd1NmMldQN0FQRUg4dmZRdEpHbUEKLS0tIGNTNWFHa0JiZE0zalNTb01EUWlD
            eDZFL3NHMnhVdW5jSktFSndaRXJnR1UKQ5tJeYJaRk/BOxzLP69RVYLxiT3mDgaU
            6nCw0BngP/yDojDu56u3auqAMqYi1unIHgClPhbNKrKNW+cE6/eqaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-28T18:37:23Z"
    mac: ENC[AES256_GCM,data:aEMel3i/LLCWoEBBmc/Y4wF9k1w3VX3ud4oQYwhqfWW0p/Y0QhcfaLyXmAhSPMC81hCtltozb9dCSFC/+08SZBnlwE+BfXT4zg6+7e8xApg3O1n0gARJ9WHovgtPGnKiCma+cEeXphoLGK+TN9H2qQ75yHbj8f9WeIbBp6adwAE=,iv:pbNkD7xgzwfIR5zTXt8q+UMEAg/F/xom/28+fTqHUp4=,tag:H+Aofb6DW4y/cqIgFN3mBw==,type:str]
    pgp: []
    encrypted_regex: ^(.*hash.*|.*apiKey.*|.*password.*|.*PHOTOPRISM.*|.*USER.*|.*PASS.*|.*users.*|.*TOKEN.*|.*Address.*|.*PrivateKey.*|.*DNS.*|.*PostUp.*|.*PublicKey.*|.*PresharedKey.*|.*Endpoint.*)$
    version: 3.8.1
