pageInfo:
    title: Corsaire Labs
    description: Health
    logo: /img/corsaire.png
    footerText: <a data-v-001d966c="" href="https://github.com/maxpoullain/homelab" target="_blank">Corsaire Labs source code</a>
sections:
    - name: Restricted access
      icon: fas fa-ban
      displayData:
        showForUsers:
            - noone
      items:
        - title: Login
          icon: fas fa-user
          description: Please login
          url: https://www.corsaire.duckdns.org/login
          target: sametab
    - name: System Alerts
      icon: fas fa-sensor-alert
      displayData:
        hideForGuests: true
        cols: 2
      widgets:
        - type: gl-alerts
          options:
            hostname: https://health.corsaire.duckdns.org
            username: max
            password: ENC[AES256_GCM,data:4Z7J/V4B30+fJA==,iv:OHx/vHcjnd4/DJ89r4IxDLZ4wlr2GPDe55JlXJcPEMI=,tag:rXQRRWH6oNpGR/9Zi1BVew==,type:str]
    - name: Client IP
      icon: fas fa-desktop
      displayData:
        hideForGuests: true
      widgets:
        - type: public-ip
    - name: IP Addresses
      icon: fas fa-globe
      displayData:
        hideForGuests: true
      widgets:
        - type: gl-ip-address
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: max
                password: ENC[AES256_GCM,data:YzUyc7NmX6Qz6g==,iv:Ut7r3z56qpSwgUsDwwmt3e8OrLONVoQ7JIPQhQJXNaA=,tag:xjkmC5SWGNwVmtLSoZhueQ==,type:str]
    - name: CPU Usage
      icon: fas fa-tachometer
      displayData:
        hideForGuests: true
        rows: 2
      widgets:
        - type: gl-current-cpu
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: max
                password: ENC[AES256_GCM,data:ToVLp2TwxQWjIA==,iv:iKG1+XwSbzal0RhHUXQll0vCwFznANqka6bDJTQw5ro=,tag:cuklzjMDMJ0KFt6yxLMRDA==,type:str]
        - type: gl-cpu-temp
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: max
                password: ENC[AES256_GCM,data:wL0zGhq/rj7NXg==,iv:G53j/EwwiYMsfXEyWHI3El3L14a3/uR14ns6qGdAgTs=,tag:u9Ql7LsU4YLRT2fSAxANlA==,type:str]
          units: C
        - type: gl-current-cores
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: max
                password: ENC[AES256_GCM,data:/HzUCysR3j34aw==,iv:IJCcj/SvmBt8tekTCJkI17wK07p61uQBcm0lpUXtntQ=,tag:YwV47HxEpshnSjp1omu4QA==,type:str]
    - name: CPU History
      icon: fas fa-microchip
      displayData:
        hideForGuests: true
        cols: 2
      widgets:
        - type: gl-cpu-history
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: max
                password: ENC[AES256_GCM,data:8NpFzTn5bi4aMg==,iv:Dhe/cjFFCgRahZRQ62MwIgxkyAZLwMey1mxT2wk9WUk=,tag:8V7vjItOHZu+bnAy5wvHLA==,type:str]
            limit: 60
    - name: Disk Space
      icon: fas fa-hdd
      displayData:
        hideForGuests: true
      widgets:
        - type: gl-disk-space
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: max
                password: ENC[AES256_GCM,data:qBS6AGGiwjc4NA==,iv:s8BiQhCHyNibnRGtvMSA7WNzpAtnQJuAZvlcs4QWd2k=,tag:uVW94c5HQipvf/Ygh130Rg==,type:str]
    - name: Memory Usage
      icon: fas fa-memory
      displayData:
        hideForGuests: true
      widgets:
        - type: gl-current-mem
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: max
                password: ENC[AES256_GCM,data:o55gfIblo7zLcw==,iv:Vjeuagrx+Kbv/D3nq9TFVTvPJb1R+mCujAOsxf1339w=,tag:tz4tDiuu6Ht7ar6dZfWWIg==,type:str]
    - name: System Load
      icon: fas fa-tasks-alt
      displayData:
        hideForGuests: true
      widgets:
        - type: gl-system-load
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: max
                password: ENC[AES256_GCM,data:amLmJM7EX1UgkA==,iv:psdPEuaK6ssprn55Yo0BFxNQx/zljrM8lyE32PVMgf8=,tag:REPkVXMOShbfLAatBpx3uA==,type:str]
    - name: Disk IO
      icon: fas fa-disc-drive
      displayData:
        hideForGuests: true
      widgets:
        - type: gl-disk-io
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: max
                password: ENC[AES256_GCM,data:8aUBOzMxPS0haA==,iv:DnitAi2wOBNO57burKTEssYRvHIrVYB2lmBuwLDc39s=,tag:qxtnE8/UJ3ke1ZtJpT3axw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146kmjfn0h64zzchtp908lx7ln8mg8agt0ree7yurvev34veaqp5s0j9kaw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWGd5dmVIY3hiVFR0ZTlT
            STVacEZqWHVZMG80OXR2bmhLelU1a3Q1MlRrCmlrOW5pMXAzbzZvV1pjaGxsRmQ4
            REhOVXlWNUNSaUxYa0RzYXJkOWRadGsKLS0tIEg4UUp6d0RWazlYUjRGbFI1cmc2
            bXZTbFZIdXMvVVRBdEYrWjIzR1FnaW8KoiPOrDDxKwjYpkP6kS2C/OWsDrxHMaYR
            BW2bajdTIG1w2Z3bHXEodMoumbvG95YC0UZMU9k3WJqurDRZDgA9AQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-16T03:51:06Z"
    mac: ENC[AES256_GCM,data:zh2+P+90QjAOTBze5DmRF1juYMR/W1BbvWxqDitnG8l9iz3Gi3vwCQazSld7tkieMTeCdBz1LRAemfmNK+zx6as6dfLYOLN8/NGN7Zw1LEU5qqRs1tnCitTID/A30TCkB1/qAFx8kC9Ld5QR7EQ/GXmhem9mydEa2yFtbCY+HPw=,iv:8r/CJ/by2pCeQ8dNmjFQ33VN0bEiZZBMHA/47J/3ahY=,tag:ffbRUKbXOjecL/NaWVmHKA==,type:str]
    pgp: []
    encrypted_regex: ^(.*hash.*|.*apiKey.*|.*password.*|.*DB_PASSWORD.*|.*USER.*|.*PASS.*|.*users.*|.*TOKEN.*|.*DNS.*|.*POST_UP.*|.*PRE_DOWN.*)$
    version: 3.8.1
