pageInfo:
    title: Corsaire Labs
    description: Health
    logo: /img/corsaire.png
    footerText: <a data-v-001d966c="" href="https://github.com/maxpoullain/homelab" target="_blank">Corsaire Labs source code</a>
sections:
    - name: Restricted access
      icon: fas fa-ban
      displayData:
        showForUsers:
            - noone
      items:
        - title: Login
          icon: fas fa-user
          description: Please login
          url: https://www.corsaire.duckdns.org/login
          target: sametab
    - name: System Alerts
      icon: fas fa-sensor-alert
      displayData:
        hideForGuests: true
        cols: 2
      widgets:
        - type: gl-alerts
          options:
            hostname: https://health.corsaire.duckdns.org
            username: max
            password: ENC[AES256_GCM,data:yFDdvYxDRj6ALg==,iv:OAwqoBXStSzS0OC0ODDlquSJYy/amxeYDth2aNNGFI8=,tag:1IOnGOW0E80fox+hqGb6bw==,type:str]
    - name: Client IP
      icon: fas fa-desktop
      displayData:
        hideForGuests: true
      widgets:
        - type: public-ip
    - name: IP Addresses
      icon: fas fa-globe
      displayData:
        hideForGuests: true
      widgets:
        - type: gl-ip-address
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: max
                password: ENC[AES256_GCM,data:hP9pRcYvIJqwew==,iv:ttdcEcCNu5P8Ijy7r0fnffAG31YV2QsbFy7gQDrXUp4=,tag:GEfbpqOMjh1/jWSgGf7x0A==,type:str]
    - name: CPU Usage
      icon: fas fa-tachometer
      displayData:
        hideForGuests: true
        rows: 2
      widgets:
        - type: gl-current-cpu
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: max
                password: ENC[AES256_GCM,data:oEUbdDJSoTLdQQ==,iv:hfKKpkTlryhZPF6zD0wub3RA2tKZeyKdf26DJbi7zrI=,tag:wH5fbQiZP+FKmw8cPvBbCA==,type:str]
        - type: gl-cpu-temp
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: max
                password: ENC[AES256_GCM,data:wZNvXZVklmmu6g==,iv:cG4wXL9u+O1WkhxuAM5IDz+i2ygfhAq+4dCmcnTqVQA=,tag:EUTvfbdgSqxELsTVDG8sug==,type:str]
          units: C
        - type: gl-current-cores
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: max
                password: ENC[AES256_GCM,data:5VW1ymq8NVcjrg==,iv:tEqSRp4/BA+eEirwC4kYec+7yK33WRsC4pqcvvIhFAs=,tag:i6sTQSR+P5kLiE1KkSybEA==,type:str]
    - name: CPU History
      icon: fas fa-microchip
      displayData:
        hideForGuests: true
        cols: 2
      widgets:
        - type: gl-cpu-history
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: max
                password: ENC[AES256_GCM,data:CQJHsk94XBY9og==,iv:IJg5YBsr8yC1Qly/iRnnSRLJJYc4iRBrjXR2KMBmwM8=,tag:R/8v0riC/9/EE3QOvvA1Rg==,type:str]
            limit: 60
    - name: Disk Space
      icon: fas fa-hdd
      displayData:
        hideForGuests: true
      widgets:
        - type: gl-disk-space
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: max
                password: ENC[AES256_GCM,data:aeN6pvP7oCRmMg==,iv:gIxU7zFwRbPQSxIc4cuMNK/bMH+I2BKTsXqpZwX7T9k=,tag:YrvAVZxEDYF0RFQ7X/XPxQ==,type:str]
    - name: Memory Usage
      icon: fas fa-memory
      displayData:
        hideForGuests: true
      widgets:
        - type: gl-current-mem
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: max
                password: ENC[AES256_GCM,data:sD4vHZatJ11YBQ==,iv:LfTkMHwF/951jAT8peG3zIdTUVRw3NXnwzzbSI8kTkQ=,tag:fmTj7c9nTUGts3u3wQFSSA==,type:str]
    - name: System Load
      icon: fas fa-tasks-alt
      displayData:
        hideForGuests: true
      widgets:
        - type: gl-system-load
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: max
                password: ENC[AES256_GCM,data:TV9XRrP6VGfbpQ==,iv:Oux5YMLp72vdX0HRZDvPbbRbPU7hrZIXv4nq3voUvIA=,tag:ZjD2tau1IsW2PVSzBwyqwg==,type:str]
    - name: Disk IO
      icon: fas fa-disc-drive
      displayData:
        hideForGuests: true
      widgets:
        - type: gl-disk-io
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: max
                password: ENC[AES256_GCM,data:jMqMUB2fmbS+OQ==,iv:XopI6fIdwvSFF/t6qQbE66hkLXhoIHIAtOe5MDek1iE=,tag:Tse1CE98+VjMHVjRffS2+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146kmjfn0h64zzchtp908lx7ln8mg8agt0ree7yurvev34veaqp5s0j9kaw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydjU4aS9xSHE4c3N3RHJs
            NDlyUGIzV3MrZ1RLRksxVVlIN2FmNkhkRFFRCkVYNks4WU5qaUMrTWlSUFo4TUdD
            aExBYWpsUVBvK2ZFVE1sY2o5V0lmZEEKLS0tIGRGQWZaaitBSmJTdklTa3BFRVNI
            dXpYL2p4UGV6VGZRS080bEM2c2pKQnMKQYh+csdjRxQXdSU5ysdnClbSMySrFHSF
            o5dXgMQN6pAnYZtY1VpOdUYS+OvL9Zt+duBvQaa+3tdNbPZEw3ypOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T12:17:18Z"
    mac: ENC[AES256_GCM,data:3uvYp7GYzB2x1RY2RiRUpG+/E6ij7jV4P7lzDtPJhBxEaCjbzjIJKg59TbdZbKjjHvwnEovoxF4sfc2aWsiXwIHJxx3UrV1KHPkEc1D1IAFsRPfDs9lxEXjNG+5X25oF+6n7/icrxesBbV4z2HFquTt5Q9CoA6icz76DCHTecwk=,iv:5h1sKGdtG5KaQd1unoVrSvE5SDuqa/nr2XdOj8tOLFA=,tag:GqtE3vwAcnMSquDJ0arwbA==,type:str]
    pgp: []
    encrypted_regex: ^(.*hash.*|.*apiKey.*|.*password.*|.*DB_PASSWORD.*|.*USER.*|.*PASS.*|.*users.*|.*TOKEN.*|.*DNS.*|.*POST_UP.*|.*PRE_DOWN.*)$
    version: 3.9.1
