pageInfo:
    title: Corsaire Labs
    description: Health
    logo: /img/corsaire.png
    footerText: <a data-v-001d966c="" href="https://github.com/maxpoullain/homelab" target="_blank">Corsaire Labs source code</a>
sections:
    - name: Restricted access
      icon: fas fa-ban
      displayData:
        showForUsers:
            - noone
      items:
        - title: Login
          icon: fas fa-user
          description: Please login
          url: https://www.corsaire.duckdns.org/login
          target: sametab
    - name: System Alerts
      icon: fas fa-sensor-alert
      displayData:
        hideForGuests: true
        cols: 2
      widgets:
        - type: gl-alerts
          options:
            hostname: https://health.corsaire.duckdns.org
            username: glances
            password: ENC[AES256_GCM,data:lyYdYdCniEBFf4p9y1SlbQ==,iv:OtxdBdTB6drqtOag/X+2w3IDs3Y4rvnLnakeX2bArLA=,tag:rD7zIyztClvftmoTy7Ibbw==,type:str]
    - name: Client IP
      icon: fas fa-desktop
      displayData:
        hideForGuests: true
      widgets:
        - type: public-ip
    - name: IP Addresses
      icon: fas fa-globe
      displayData:
        hideForGuests: true
      widgets:
        - type: gl-ip-address
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: glances
                password: ENC[AES256_GCM,data:NhYeKCHtzRE+BspZzo8V8A==,iv:mqqDeU2uN+ryNJba9uWZWUA20v0FuL4GnzmMfu5lVts=,tag:d/vDmnfqpfelifbeVSPe/g==,type:str]
    - name: CPU Usage
      icon: fas fa-tachometer
      displayData:
        hideForGuests: true
        rows: 2
      widgets:
        - type: gl-current-cpu
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: glances
                password: ENC[AES256_GCM,data:7Ws0EYaJVxcuK5szaJCheQ==,iv:mm1VMy5e4WlPRdubPy+dMpV4lRt8ncXdnB5UWd/7cjQ=,tag:xn3FIL3X0hTmtn49bSPWSA==,type:str]
        - type: gl-cpu-temp
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: glances
                password: ENC[AES256_GCM,data:LVjOiok5krIZliIllYHG5w==,iv:hVfQsWcvBEYlTMcYznwO8GNYEXPsuDMgob53DdMnHAg=,tag:ZjaRusZtFkRXIFKnAyAr/w==,type:str]
          units: C
        - type: gl-current-cores
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: glances
                password: ENC[AES256_GCM,data:yxDWLUbrUrX16IkF/wpRwg==,iv:f+gLaoh/BOlR62n7UiNzroTG3ZayC/TdY3Ie8412EU8=,tag:DXPSY0zTA5ES9ipGUuP0MA==,type:str]
    - name: CPU History
      icon: fas fa-microchip
      displayData:
        hideForGuests: true
        cols: 2
      widgets:
        - type: gl-cpu-history
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: glances
                password: ENC[AES256_GCM,data:sh5K9JQa2olJzbFHHfyuwQ==,iv:erFCfDUF+55wgKmlrib8gLgsCU9yywQE7KmHezKwNiM=,tag:31tjs64xcGlYZsdecEmooQ==,type:str]
            limit: 60
    - name: Disk Space
      icon: fas fa-hdd
      displayData:
        hideForGuests: true
      widgets:
        - type: gl-disk-space
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: glances
                password: ENC[AES256_GCM,data:I6hWXoE6KfJTsaAOffqiKw==,iv:E01SlOeXuVDf45pUzl34EWrKjx5/TQDYGCqqh1kKB9U=,tag:Rjfaw4VCG+w8TP01gD2lBA==,type:str]
    - name: Memory Usage
      icon: fas fa-memory
      displayData:
        hideForGuests: true
      widgets:
        - type: gl-current-mem
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: glances
                password: ENC[AES256_GCM,data:lp4laAU3mKaE7iFGpILtrQ==,iv:A26DTJCOJgEnVk4bL6Q/VW/Ank+bcBotUi7RUaRSqNM=,tag:Nftd8CdvUNPpQP7yToQL3w==,type:str]
    - name: System Load
      icon: fas fa-tasks-alt
      displayData:
        hideForGuests: true
      widgets:
        - type: gl-system-load
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: glances
                password: ENC[AES256_GCM,data:g/NdjQfGb5qNDcB9tDmPag==,iv:4vQDSkjqn7EFzX4DxoCnk7bjliEPigLZ7VS75XsUJMY=,tag:y12Y2Ojkwmdv0nPcO9tPCQ==,type:str]
    - name: Disk IO
      icon: fas fa-disc-drive
      displayData:
        hideForGuests: true
      widgets:
        - type: gl-disk-io
          options:
            !!merge <<:
                hostname: https://health.corsaire.duckdns.org
                username: glances
                password: ENC[AES256_GCM,data:QR/fb725nD7H5slQcSiiEg==,iv:PD1zqugPVKnqw0lfBrps6XMyc4YFNFAf4Oa66veODyM=,tag:X96GTun1UZOxnsyvlK+z7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146kmjfn0h64zzchtp908lx7ln8mg8agt0ree7yurvev34veaqp5s0j9kaw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYmdHRUZLT3hTWmZSMHcz
            dHd3VXZyamx5VS9BUC9JUWJ0d1VTNUIyb0JzCkRwRHVKZHdBYjVDcko1blhKeFdJ
            djhTQ2E5TGRJUmRTWFlFY0oydU9qSm8KLS0tIEpVcHZWaWpXRkRqc0Voak10WDFL
            a0VsTmwvZXhxdHYwaElKMnIwVVMzdUEKOgQ4osUMVC2vLhs10QlF2Rz7XDAQaNmh
            pvZuWBg++mZuz0USqa4ZBoURoAbtiW28ZUPyxnTsodvFp+PZR+e4NQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T15:49:04Z"
    mac: ENC[AES256_GCM,data:jUXFq87vjXYFus7jJAOkA/81mEPiZSaHnQ3twBUJD23nEU9BSw4gSD5EA7vgCwSV3Qhujmyfqfxba+A1aO2OCVp++fWdD/nqxM5vUwhdVFZmMJRFrDJ8rsz/eZJOr0/wJ4U6aWCrbTI8H/lmHdEL35dMZbqrSWkyODeafi+MgXs=,iv:IFlaWraX2wwqDMPZ7ESPkxsOxhq3dsQVCSjzqA1fCL4=,tag:n8GCoLl044LXOXceyLt5bg==,type:str]
    pgp: []
    encrypted_regex: ^(.*hash.*|.*apiKey.*|.*password.*|.*DB_PASSWORD.*|.*USER.*|.*PASS.*|.*users.*|.*TOKEN.*|.*DNS.*|.*POST_UP.*|.*PRE_DOWN.*)$
    version: 3.9.1
