pageInfo:
    title: Corsaire Labs
    description: Health
    logo: /img/corsaire.png
    footerText: <a data-v-001d966c="" href="https://github.com/maxpoullain/homelab" target="_blank">Corsaire Labs source code</a>
sections:
    - name: Restricted access
      icon: fas fa-ban
      displayData:
        showForUsers:
            - noone
      items:
        - title: Login
          icon: fas fa-user
          description: Please login
          url: https://www.corsaire.duckdns.org/login
          target: sametab
    - name: System Alerts
      icon: fas fa-sensor-alert
      displayData:
        hideForGuests: true
        cols: 2
      widgets:
        - type: gl-alerts
          options:
            hostname: https://health.corsaire.duckdns.org
            username: glances
            password: ENC[AES256_GCM,data:gQ12T4YMnX23KaHV7DZ6yg==,iv:5+kmn6QH5e6JsjwcF6kRAAjEvpr+xCOoXtmOzNz4NZA=,tag:1052da5E+qnDGSyE5re7ig==,type:str]
    - name: Client IP
      icon: fas fa-desktop
      displayData:
        hideForGuests: true
      widgets:
        - type: public-ip
    - name: IP Addresses
      icon: fas fa-globe
      displayData:
        hideForGuests: true
      widgets:
        - type: gl-ip-address
          options:
            hostname: https://health.corsaire.duckdns.org
            username: glances
            password: ENC[AES256_GCM,data:WhMbvAH6KETt6gEBHz4T7Q==,iv:lb+OG5yYrsPfnNWnbCDijfnxd8lyUHeuMukeAC0eNV0=,tag:9qwMOVCLNoRfSHAhbXWgJA==,type:str]
    - name: CPU Usage
      icon: fas fa-tachometer
      displayData:
        hideForGuests: true
        rows: 2
      widgets:
        - type: gl-current-cpu
          options:
            hostname: https://health.corsaire.duckdns.org
            username: glances
            password: ENC[AES256_GCM,data:O+p20tiYy1npkSwjY1rvEA==,iv:tEf+H58wgeVBniRHYenZEcRnb1g2yhufwAUDmqYPeXo=,tag:rBzsWDFTi7NJL4ZUDHdIAw==,type:str]
        - type: gl-cpu-temp
          options:
            hostname: https://health.corsaire.duckdns.org
            username: glances
            password: ENC[AES256_GCM,data:4FN8wDAHEif60sVVp9iLKQ==,iv:wWYQZI/PBvyT6dAilVd5tswvcEtKAsjQO0Ms7Uj++x8=,tag:+iIjNRsDX59vPQ2d+G1wiA==,type:str]
          units: C
        - type: gl-current-cores
          options:
            hostname: https://health.corsaire.duckdns.org
            username: glances
            password: ENC[AES256_GCM,data:VjvBhgU5gptHW0zGg0h6/w==,iv:xPaOabnjTPmpE4EpWZV3yKMvNGORgnXR3V3Zji/C3gc=,tag:mfoBToeTjzGi1em3zSjtdw==,type:str]
    - name: CPU History
      icon: fas fa-microchip
      displayData:
        hideForGuests: true
        cols: 2
      widgets:
        - type: gl-cpu-history
          options:
            hostname: https://health.corsaire.duckdns.org
            username: glances
            password: ENC[AES256_GCM,data:5IFfcNaBNV9V0hiFLfygaA==,iv:n/H14YoNl5zyaLsV6zvIWiCG9LztjMqMB0W4RC08vlQ=,tag:xAHGJBJFQO9BCHiqmgbsbw==,type:str]
            limit: 60
    - name: Disk Space
      icon: fas fa-hdd
      displayData:
        hideForGuests: true
      widgets:
        - type: gl-disk-space
          options:
            hostname: https://health.corsaire.duckdns.org
            username: glances
            password: ENC[AES256_GCM,data:3OaMGg83ZgEUARloZurO1Q==,iv:fD5u78bjYGkBvZBcDlrA4/9ghwZ2S8kqNmC9SU5cazc=,tag:sExGRaxEMNYoIZlqQ9eAUQ==,type:str]
    - name: Memory Usage
      icon: fas fa-memory
      displayData:
        hideForGuests: true
      widgets:
        - type: gl-current-mem
          options:
            hostname: https://health.corsaire.duckdns.org
            username: glances
            password: ENC[AES256_GCM,data:oF7Iuu5AxzxTY6B6912vWQ==,iv:2K7mI7lFiEUdmdRRR87lIgzTilObFgIHsrDnpEMPg+0=,tag:q5q6/8ywTzmVPW4EE80G7w==,type:str]
    - name: System Load
      icon: fas fa-tasks-alt
      displayData:
        hideForGuests: true
      widgets:
        - type: gl-system-load
          options:
            hostname: https://health.corsaire.duckdns.org
            username: glances
            password: ENC[AES256_GCM,data:QjOCqaMlyqhWGqo6BmkEfw==,iv:fb2AA6wGO+/H25LfxR2yAyQk374X8kCFlrFMTSei0Yk=,tag:z/vtXcPAd8jszk7gvfZCiQ==,type:str]
    - name: Disk IO
      icon: fas fa-disc-drive
      displayData:
        hideForGuests: true
      widgets:
        - type: gl-disk-io
          options:
            hostname: https://health.corsaire.duckdns.org
            username: glances
            password: ENC[AES256_GCM,data:fCRR0D7kKaBrzURkeFNdXg==,iv:vgSLnYWUhQuwHCwe1si736aogsL6J3qquf74N9o2Otk=,tag:RL7t5SxWgW/U3SRG4/M5SA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146kmjfn0h64zzchtp908lx7ln8mg8agt0ree7yurvev34veaqp5s0j9kaw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWncxWXpON0U1SFd6ckJx
            YVBSUzRvTm5iZ0dsbVlPaWVWVzQxbGVCcGowCmFNS2RMa3NkSFkwbXZQWlM0YXZG
            NTFQNWw1Vk15R1g2Y1phZW5RZFZJL0EKLS0tIE5ndjhOZnYzUmVDd0tGV1RTUlhI
            TDA5aHhYZGRjbkZQeWpkMHpVR3RRQnMKdEh2sK1SPpcKnLXloQ15YpFlhy9ejl6b
            sgq6i9QZOhkN3WSTgy9cl3STFR4O4wr9pn8DXxx4xtlNU1zHIAutog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T09:13:57Z"
    mac: ENC[AES256_GCM,data:2Sp3IvK1dfIFitZSzmQGTjTzC64BEGFc8IeG+M3OIlDvfKTUhdWmhnJbvBmfVHx33aObKu/UmvgV6qGrrXyOEcsPlPe0e3uI0MQRXO4fcWmtCup215B8EKJq4GF8odD5ZVUQ2/Bfx/buhJrn5FsoGTyLyBduwChsLzfqOlShOis=,iv:KppO0GTj2o+jNSkIn2rQUJ+Y0XXwaQe5ILs1s3aNIg4=,tag:UCbW5gLGfldlgdhxuFemUg==,type:str]
    pgp: []
    encrypted_regex: ^(.*hash.*|.*apiKey.*|.*password.*|.*DB_PASSWORD.*|.*USER.*|.*PASS.*|.*users.*|.*TOKEN.*|.*DNS.*|.*POST_UP.*|.*PRE_DOWN.*)$
    version: 3.9.1
