---
pageInfo:
  title: Corsaire Labs
  description: Hobbies
  logo: /img/corsaire.png
  footerText: <a data-v-001d966c="" href="https://github.com/maxpoullain/homelab" target="_blank">Corsaire Labs source code</a>

sections:

  - name: Restricted access
    icon: fas fa-ban
    displayData:
      showForUsers: [noone]
    items:
      - title: Login
        icon: fas fa-user
        description: "Please login"
        url: https://www.corsaire.duckdns.org/login
        target: sametab

  - name: 3D
    icon: fas fa-cubes
    displayData:
      hideForGuests: true
    items:
      - title: Printables
        icon: favicon
        description: "Discover, download and print thousands of 3D models"
        url: https://www.printables.com/
      - title: Thingiverse
        icon: favicon
        description: "Download files and build them with your 3D printer, laser cutter, or CNC"
        url: https://www.thingiverse.com/
      - title: Tinkercad
        icon: favicon
        description: "KidSAFE-certified online platform that lets you create 3D digital designs"
        url: https://www.tinkercad.com/

  - name: Gaming
    icon: fas fa-gamepad
    displayData:
      hideForGuests: true
    items:
      - title: Lorem ipsum
        icon: favicon
        description: "Lorem ipsum"
        url: https://www.lipsum.com/
      - title: Lorem ipsum
        icon: favicon
        description: "Lorem ipsum"
        url: https://www.lipsum.com/

  - name: TCG
    icon: fas fa-dice
    displayData:
      hideForGuests: true
      rows: 3
    items:
      - title: Collectr
        icon: favicon
        description: "Get ready for the next-generation of collectible portfolio management."
        url: https://app.getcollectr.com/
      - title: Shiny Live
        icon: favicon
        description: "Vente aux enchères en direct"
        url: https://web.shiny-app.live/
      - title: OP Limitless TCG
        icon: favicon
        description: "Aiming to provide all the content and information about TCG needs"
        url: https://onepiece.limitlesstcg.com/
      - title: OPECards
        icon: favicon
        description: "Site communautaire référence du jeu de cartes à collectionner One Piece Card Game"
        url: https://www.opecards.fr/
      - title: Cardmarket
        icon: favicon
        description: "Ultimate online destination for buying and selling trading cards"
        url: https://www.cardmarket.com/
      - title: Maxi Rêves
        icon: favicon
        description: "Card shop"
        url: https://maxireves.fr/
      - title: Fantasy Sphere
        icon: favicon
        description: "La boutique specialisée dans les cartes à collectionner, Pokémon Yu-Gi-Oh! Magic, Disney Locarna, One Piece, TCG et les jeux de sociétés."
        url: https://www.fantasysphere.net/
      - title: Games Avenue
        icon: favicon
        description: "Card shop"
        url: https://gamesavenue.fr/
      - title: E-CardStore
        icon: favicon
        description: "Vente TCG"
        url: https://ecardstore.fr/
      - title: InvestCollect
        icon: favicon
        description: "La Ligue du Jeu by Invest Collect "
        url: https://investcollect.com/
      - title: Le Coin Des Barons
        icon: favicon
        description: "Magasin spécialisé dans la vente de produits TCG"
        url: https://lecoindesbarons.com/

  - name: F1
    icon: fas fa-flag-checkered
    displayData:
      hideForGuests: true
      rows: 4
      itemSize: large
    items:
      - title: F1 TV
        icon: f1tv.png
        description: "Enter the world of Formula 1"
        url: https://f1tv.formula1.com/
      - title: F1 Calendar
        icon: favicon
        description: "Races, Qualifying & Practice Sessions"
        url: https://f1calendar.com/
    widgets:
      - type: sports-scores
        options:
          leagueId: 4370
          pastOrFuture: future
          limit: 5
          hideImage: false

  - name: Karting
    icon: fas fa-trophy
    displayData:
      hideForGuests: true
    items:
      - title: ASK Laval
        icon: favicon
        description: "Disponibilité Circuit Beausoleil"
        url: https://www.karting-laval.fr/disponibilite-circuit/
      - title: EvoKart
        icon: favicon
        description: "Constructeur de karting de compétition et organisation de courses sprint et endurance"
        url: http://www.evokart-france.com/
      - title: Karting KFS
        icon: favicon
        description: "FB KFS"
        url: https://www.facebook.com/groups/1105901062824211/
      - title: Mondokart
        icon: favicon
        description: "Go-Kart online shop"
        url: https://www.mondokart.com/
      - title: FFSA
        icon: favicon
        description: "French Federation of Automobile Sport"
        url: https://licence.ffsa.org/
