---
pageInfo:
  title: Corsair Labs
  description: Work
  logo: /img/corsaire.png
  footerText: <a data-v-001d966c="" href="https://github.com/maxpoullain/homelab" target="_blank">Corsaire Labs source code</a>
sections:

  - name: Restricted access
    icon: fas fa-ban
    displayData:
      showForUsers: [noone]
    items:
      - title: Login
        icon: fas fa-user
        description: "Please login"
        url: https://www.corsaire.duckdns.org/login
        target: sametab
