services:

  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin:latest
    restart: unless-stopped
    mem_limit: 3072m
    security_opt:
      - no-new-privileges:true
    group_add:
      - "44"
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
    networks:
      - traefik
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    volumes:
      - ./jellyfin/config:/config
      - /mnt/nas/media/Shows:/shows
      - /mnt/nas/media/Movies:/movies
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entrypoints=https"
      - "traefik.http.routers.jellyfin.rule=Host(`tv.corsaire.duckdns.org`)"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.tls.certresolver=acme"
      - "traefik.http.routers.jellyfin.tls.domains=tv.corsaire.duckdns.org"
      - "traefik.http.routers.jellyfin.middlewares=jellyfin"
      - "traefik.http.middlewares.jellyfin.headers.customResponseHeaders.X-Robots-Tag=noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
      - "traefik.http.middlewares.jellyfin.headers.SSLRedirect=true"
      - "traefik.http.middlewares.jellyfin.headers.SSLHost=tv.corsaire.duckdns.org"
      - "traefik.http.middlewares.jellyfin.headers.SSLForceHost=true"
      - "traefik.http.middlewares.jellyfin.headers.STSSeconds=315360000"
      - "traefik.http.middlewares.jellyfin.headers.STSIncludeSubdomains=true"
      - "traefik.http.middlewares.jellyfin.headers.STSPreload=true"
      - "traefik.http.middlewares.jellyfin.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.jellyfin.headers.frameDeny=true"
      - "traefik.http.middlewares.jellyfin.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.jellyfin.headers.browserXSSFilter=true"
      - "traefik.http.middlewares.jellyfin.headers.customFrameOptionsValue='allow-from https://corsaire.duckdns.org'"
      - "traefik.http.routers.jellyfin.service=jellyfin"
      - "traefik.http.services.jellyfin.loadBalancer.server.port=8096"
      - "traefik.http.services.jellyfin.loadBalancer.passHostHeader=true"

networks:
  traefik:
    external: true
