site_name: Corsaire Wiki
site_url: https://wiki.corsaire.duckdns.org
repo_url: https://github.com/maxpoullain/homelab
repo_name: maxpoullain/homelab
theme:
  name: material
  logo: https://www.corsaire.duckdns.org/img/corsaire.png
  favicon: https://www.corsaire.duckdns.org/img/corsaire.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
  # - navigation.footer
  - content.code.copy
extra_css:
  - stylesheets/extra.css
extra:
  # social:
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/maxpoullain
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
