#  to NAS

[http.routers.nas]
  entryPoints = [ "https" ]
  rule = "Host(`nas.corsaire.duckdns.org`)"
  service = "nas"
  priority = 1
  [http.routers.nas.tls]
    certResolver = "acme"

[http.services.nas.loadBalancer]
  [[http.services.nas.loadBalancer.servers]]
    url = "http://192.168.1.42:8080"
