#  to HomeAssistant

[http.routers.homeassistant]
  entryPoints = [ "https" ]
  rule = "Host(`home.corsaire.duckdns.org`)"
  service = "homeassistant"
  priority = 1
  [http.routers.homeassistant.tls]
    certResolver = "acme"

[http.services.homeassistant.loadBalancer]
  [[http.services.homeassistant.loadBalancer.servers]]
    url = "http://192.168.1.3:8123"
