version: "3.8"
services:

  photoprism:
    container_name: photoprism
    image: photoprism/photoprism:latest
    restart: unless-stopped
    stop_grace_period: 10s
    cpus: 2
    mem_limit: 3072m
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
      - no-new-privileges:true
    user: "1000:1000"
    depends_on:
      - photoprism_mariadb
    networks:
      - photoprism
      - traefik
    ## Share hardware devices with FFmpeg and TensorFlow (optional):
    devices:
      - "/dev/video11:/dev/video11" # Video4Linux (h264_v4l2m2m)
    working_dir: "/photoprism"
    volumes:
      - "./storage:/photoprism/storage"
      - "/mnt/nas/media/Photos/Max:/photoprism/originals/Max"
      - "/mnt/nas/media/Photos/Sixtine:/photoprism/originals/Sixtine"
      - "/mnt/nas/media/Photos/JD:/photoprism/originals/JD"
      - "/mnt/nas/media/Photos/Stephanie:/photoprism/originals/Stephanie"
      # Mounting the import folder is optional (see docs):
      # - "~/Import:/photoprism/import"
    env_file:
      - secrets.env
    environment:
      PHOTOPRISM_SITE_URL: "https://photos.corsaire.duckdns.org/" # public server URL incl http:// or https:// and /path, :port is optional
      PHOTOPRISM_AUTH_MODE: "password" # authentication mode (public, password)
      PHOTOPRISM_ORIGINALS_LIMIT: 8000 # file size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: "none" # improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_WORKERS: 2 # Limits the number of indexing workers to reduce system load
      PHOTOPRISM_LOG_LEVEL: "info" # log level: trace, debug, info, warning, error, fatal, or panic
      PHOTOPRISM_READONLY: "false" # do not modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false" # enables experimental features
      PHOTOPRISM_DISABLE_CHOWN: "false" # disables updating storage permissions via chmod and chown on startup
      PHOTOPRISM_DISABLE_WEBDAV: "false" # disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false" # disables Settings in Web UI
      PHOTOPRISM_DISABLE_TENSORFLOW: "false" # disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "false" # disables face detection and recognition (requires TensorFlow)
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false" # disables image classification (requires TensorFlow)
      PHOTOPRISM_DISABLE_VECTORS: "false" # disables vector graphics support
      PHOTOPRISM_DISABLE_RAW: "false" # disables indexing and conversion of RAW images
      PHOTOPRISM_RAW_PRESETS: "false" # enables applying user presets when converting RAW images (reduces performance)
      PHOTOPRISM_JPEG_QUALITY: 85 # a higher value increases the quality and file size of JPEG images and thumbnails (25-100)
      PHOTOPRISM_DETECT_NSFW: "false" # automatically flags photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true" # allow uploads that MAY be offensive
      ## Video Transcoding (https://docs.photoprism.app/getting-started/advanced/transcoding/):
      PHOTOPRISM_FFMPEG_ENCODER: "h264_v4l2m2m" # H.264/AVC encoder (software, intel, nvidia, apple, raspberry, or vaapi)
      PHOTOPRISM_FFMPEG_SIZE: "1920" # video size limit in pixels (720-7680) (default: 3840)
      PHOTOPRISM_FFMPEG_BITRATE: "32" # video bitrate limit in Mbit/s (default: 50)
      PHOTOPRISM_FFMPEG_BUFFERS: "64" # FFmpeg capture buffers (default: 32)
      ## Database settings
      PHOTOPRISM_DATABASE_DRIVER: "mysql" # use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "photoprism_mariadb:3306" # MariaDB or MySQL database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism" # MariaDB or MySQL database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism" # MariaDB or MySQL database user name
      PHOTOPRISM_DATABASE_PASSWORD: "insecure" # MariaDB or MySQL database user password
      ## Description
      PHOTOPRISM_SITE_TITLE: "Corsaire pics"
      PHOTOPRISM_SITE_CAPTION: "Corsaire life in pictures"
      # PHOTOPRISM_SITE_DESCRIPTION: ""
      # PHOTOPRISM_SITE_AUTHOR: ""
      ## Run/install on first startup (options: update, gpu, tensorflow, davfs, clean):
      # PHOTOPRISM_INIT: "update clean"
      ## Run as a specific user, group, or with a custom umask (does not work together with "user:")
      HOME: "/photoprism"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.photos.entrypoints=https"
      - "traefik.http.routers.photos.rule=Host(`photos.corsaire.duckdns.org`)"
      - "traefik.http.routers.photos.tls=true"
      - "traefik.http.routers.photos.tls.certresolver=acme"
      - "traefik.docker.network=traefik"

  ## Photoprism Database Server
  ## see https://docs.photoprism.app/getting-started/faq/#should-i-use-sqlite-mariadb-or-mysql
  photoprism_mariadb:
    container_name: photoprism_mariadb
    image: arm64v8/mariadb:10.11
    restart: unless-stopped
    stop_grace_period: 5s
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
      - no-new-privileges:true
    command: --innodb-buffer-pool-size=256M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    ## Never store database files on an unreliable device such as a USB flash drive, an SD card, or a shared network folder:
    volumes:
      - "./mariadb:/config" # important, don't remove
    env_file:
      - secrets.env
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_DATABASE: "photoprism"
      MARIADB_USER: "photoprism"
      MARIADB_PASSWORD: "insecure"
      MARIADB_ROOT_PASSWORD: "insecure"
    networks:
      - photoprism

networks:
  photoprism:
    external: true
  traefik:
    external: true
