version: "3.8"
services:

  photoprism:
    container_name: photoprism
    image: photoprism/photoprism:armv7
    depends_on:
      - photoprism_mariadb
    restart: unless-stopped
    user: "1000:1000"
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
      - no-new-privileges:true
    env_file:
      - secrets.env
    environment:
      PHOTOPRISM_SITE_URL: "https://photos.corsaire.duckdns.org/" # public server URL incl http:// or https:// and /path, :port is optional
      PHOTOPRISM_ORIGINALS_LIMIT: 10000 # file size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: "none" # improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_WORKERS: 2 # Limits the number of indexing workers to reduce system load
      PHOTOPRISM_DEBUG: "false" # run in debug mode (shows additional log messages)
      PHOTOPRISM_PUBLIC: "false" # no authentication required (disables password protection)
      PHOTOPRISM_READONLY: "false" # don't modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false" # enables experimental features
      PHOTOPRISM_DISABLE_CHOWN: "false" # disables storage permission updates on startup
      PHOTOPRISM_DISABLE_WEBDAV: "false" # disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false" # disables Settings in Web UI
      PHOTOPRISM_DISABLE_TENSORFLOW: "false" # disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "false" # disables facial recognition
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false" # disables image classification
      PHOTOPRISM_FFMPEG_ENCODER: "h264_v4l2m2m" # FFmpeg AVC encoder for video transcoding (default: libx264)
      PHOTOPRISM_FFMPEG_BUFFERS: "64" # FFmpeg capture buffers (default: 32)
      PHOTOPRISM_DETECT_NSFW: "false" # flag photos as private that MAY be offensive
      PHOTOPRISM_UPLOAD_NSFW: "true" # allows uploads that MAY be offensive
      # PHOTOPRISM_DATABASE_DRIVER: "sqlite"           # SQLite is an embedded database that doesn't require a server
      PHOTOPRISM_DATABASE_DRIVER: "mysql" # use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "photoprism_mariadb:3306" # MariaDB or MySQL database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism" # MariaDB or MySQL database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism" # MariaDB or MySQL database user name
      PHOTOPRISM_DATABASE_PASSWORD: "insecure" # MariaDB or MySQL database user password
      PHOTOPRISM_SITE_TITLE: "Corsaire pics"
      PHOTOPRISM_SITE_CAPTION: "Corsaire life in pictures"
      # PHOTOPRISM_SITE_DESCRIPTION: ""
      # PHOTOPRISM_SITE_AUTHOR: ""
      ## Run/install on first startup (options: update, gpu, tensorflow, davfs, clean):
      # PHOTOPRISM_INIT: "update clean"
      ## Run as a specific user, group, or with a custom umask (does not work together with "user:")
      HOME: "/photoprism"
    ## Share hardware devices with FFmpeg and TensorFlow (optional):
    devices:
      - "/dev/video11:/dev/video10"
      - "/dev/video11:/dev/video11" # Video4Linux (h264_v4l2m2m)
      - "/dev/video11:/dev/video12"
    working_dir: "/photoprism"
    volumes:
      - "./storage:/photoprism/storage"
      - "/mnt/nas/photos/Max:/photoprism/originals/Max"
      # Mounting the import folder is optional (see docs):
      # - "~/Import:/photoprism/import"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.photos.entrypoints=https"
      - "traefik.http.routers.photos.rule=Host(`photos.corsaire.duckdns.org`)"
      - "traefik.http.routers.photos.tls=true"
      - "traefik.http.routers.photos.tls.certresolver=acme"
      - "traefik.docker.network=traefik"
    networks:
      - photoprism
      - traefik

  ## Photoprism Database Server
  ## see https://docs.photoprism.app/getting-started/faq/#should-i-use-sqlite-mariadb-or-mysql
  photoprism_mariadb:
    container_name: photoprism_mariadb
    image: linuxserver/mariadb:latest
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
      - no-new-privileges:true
    ## Never store database files on an unreliable device such as a USB flash drive, an SD card, or a shared network folder:
    volumes:
      - "./mariadb:/config" # important, don't remove
    environment:
      MYSQL_ROOT_PASSWORD: insecure
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: insecure
    networks:
      - photoprism

networks:
  photoprism:
    external: true
  traefik:
    external: true
