version: '3.8'

services:
  dashy:
    container_name: dashy
    image: lissy93/dashy:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: [ 'CMD', 'node', '/app/services/healthcheck' ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - traefik
    volumes:
      - "./public:/app/public"
    environment:
      - GID=1000
      - UID=1000
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashy.entrypoints=https"
      - "traefik.http.routers.dashy.rule=Host(`dashy.corsaire.duckdns.org`, `www.corsaire.duckdns.org`, `corsaire.duckdns.org`)"
      - "traefik.http.routers.dashy.middlewares=dashy"
      - "traefik.http.routers.dashy.tls=true"
      - "traefik.http.routers.dashy.tls.certresolver=acme"
      - "traefik.http.routers.dashy.service=dashy"
      - "traefik.http.services.dashy.loadbalancer.server.port=80"
      - "traefik.http.middlewares.dashy.redirectregex.regex=https://(dashy.)?corsaire.duckdns.org"
      - "traefik.http.middlewares.dashy.redirectregex.replacement=https://www.corsaire.duckdns.org"

networks:
  traefik:
    external: true
