version: '3.8'

services:
  dashy:
    container_name: dashy
    image: lissy93/dashy:latest
    command: [ "yarn", "build-and-start" ]
    restart: unless-stopped
    cpus: 3
    mem_limit: 2048m
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: [ 'CMD', 'node', '/app/services/healthcheck' ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - traefik
    volumes:
      - "./config/conf.yml:/app/public/conf.yml"
      - "./config/work.yml:/app/public/work.yml"
      - "./config/hobbies.yml:/app/public/hobbies.yml"
      - "./config/health.yml:/app/public/health.yml"
      - "./config/icons:/app/public/item-icons"
      - "./config/themes/custom.scss:/app/src/styles/user-defined-themes.scss"
      - "./config/img/corsaire.png:/app/public/img/corsaire.png"
      - "./config/img/favicon.ico:/app/public/img/icons/favicon.ico"
      - "./config/img/favicon-16x16.png:/app/public/img/icons/favicon-16x16.png"
      - "./config/img/favicon-32x32.png:/app/public/img/icons/favicon-32x32.png"
    environment:
      - GID=1000
      - UID=1000
      - NODE_ENV=production
      - TZ=Europe/Paris
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashy.entrypoints=https"
      - "traefik.http.routers.dashy.rule=Host(`dashy.corsaire.duckdns.org`, `www.corsaire.duckdns.org`, `corsaire.duckdns.org`)"
      - "traefik.http.routers.dashy.middlewares=dashy"
      - "traefik.http.routers.dashy.tls=true"
      - "traefik.http.routers.dashy.tls.certresolver=acme"
      - "traefik.http.routers.dashy.service=dashy"
      - "traefik.http.services.dashy.loadbalancer.server.port=80"
      - "traefik.http.middlewares.dashy.redirectregex.regex=https://(dashy.)?corsaire.duckdns.org"
      - "traefik.http.middlewares.dashy.redirectregex.replacement=https://www.corsaire.duckdns.org"

networks:
  traefik:
    external: true
