services:
  dashy:
    container_name: dashy
    image: lissy93/dashy:3.x
    restart: unless-stopped
    cpus: 3
    mem_limit: 2048m
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: [ 'CMD', 'node', '/app/services/healthcheck' ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - traefik
    volumes:
      - "./config:/app/user-data"
      - "./web-icons:/app/public/web-icons"
      - "./styles/user-defined-themes.scss:/app/src/styles/user-defined-themes.scss"
    environment:
      - GID=1000
      - UID=1000
      - NODE_ENV=production
      - TZ=Europe/Paris
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashy.entrypoints=https"
      - "traefik.http.routers.dashy.rule=Host(`dashy.corsaire.duckdns.org`) || Host(`www.corsaire.duckdns.org`) || Host(`corsaire.duckdns.org`)"
      - "traefik.http.routers.dashy.middlewares=dashy"
      - "traefik.http.routers.dashy.tls=true"
      - "traefik.http.routers.dashy.tls.certresolver=acme"
      - "traefik.http.routers.dashy.service=dashy"
      - "traefik.http.services.dashy.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.dashy.redirectregex.regex=https://(dashy.)?corsaire.duckdns.org"
      - "traefik.http.middlewares.dashy.redirectregex.replacement=https://www.corsaire.duckdns.org"

networks:
  traefik:
    external: true
