services:
  dashy:
    container_name: dashy
    image: lissy93/dashy:latest
    restart: unless-stopped
    cpus: 3
    mem_limit: 2048m
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: [ 'CMD', 'node', '/app/services/healthcheck' ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - traefik
    volumes:
      - "./config:/app/user-data"
      - "./web-icons:/app/public/web-icons"
      - "./styles/user-defined-themes.scss:/app/src/styles/user-defined-themes.scss"
    environment:
      - GID=3002
      - UID=3000
      - NODE_ENV=production
      - TZ=Europe/Paris
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashy.entrypoints=https"
      - "traefik.http.routers.dashy.rule=Host(`dashy.corsair.tf`) || Host(`www.corsair.tf`) || Host(`corsair.tf`)"
      - "traefik.http.routers.dashy.middlewares=dashy"
      - "traefik.http.routers.dashy.middlewares=security-soft@file"
      - "traefik.http.routers.dashy.service=dashy"
      - "traefik.http.services.dashy.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.dashy.redirectregex.regex=https://(dashy.)?corsair.tf"
      - "traefik.http.middlewares.dashy.redirectregex.replacement=https://www.corsair.tf"

networks:
  traefik:
    external: true
