version: '3'

services:
  dashy:
    container_name: dashy
    image: lissy93/dashy:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    volumes:
      - "/data/dashy/conf.yml:/app/public/conf.yml"
      - "/data/dashy/assets/favicon/favicon.ico:/app/public/favicon.ico"
      - "/data/dashy/assets/favicon/favicon-32x32.png:/app/public/web-icons/favicon-32x32.png"
      - "/data/dashy/assets/icons:/app/public/item-icons"
      - "/data/dashy/assets:/app/public/assets"
    environment:
      - GID=1000
      - UID=1000
      - NODE_ENV=production
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashy.entrypoints=https"
      - "traefik.http.routers.dashy.rule=Host(`dashy.corsaire.duckdns.org`)"
      - "traefik.http.routers.dashy.tls=true"
      - "traefik.http.routers.dashy.tls.certresolver=acme"
      - "traefik.http.routers.dashy.service=dashy"
      - "traefik.http.services.dashy.loadbalancer.server.port=80"

networks:
  traefik:
    external: true
