# Declaring the basicauth user lists
http:
    middlewares:
        traefik-auth:
            basicAuth:
                users:
                    - ENC[AES256_GCM,data:EsQdepC2EdQ6DUBpRkCaB0IgmMfb9uBH6RxbU+LhPOI3gjGSZg==,iv:8lk+Hss++QmAVUGNST/I5aljT9BPEJY/BHi3wj0JI8Q=,tag:p9ReyZDBlCQp3oDrAsWveA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146kmjfn0h64zzchtp908lx7ln8mg8agt0ree7yurvev34veaqp5s0j9kaw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAya2JnMCsxVURLSVpyQWcy
            WERQbWFJUkJHdDZLbFE3QkVQclhXWnpnYTNrCjZIaHlBUEU1SHZyZ0JnZDZxZlVJ
            citITm0rTC9IMjBQM29PZml2NjZ4aG8KLS0tIFJpcU8yS2s1eThBQmpaTjhNWWFQ
            M2llbjR1eU9Mc1NpbHpwbGpyWEZ1UUkKVrpI3kqABz28Fi/buXH7A46rzwuHsCv7
            kMFfqe3XKx3Fm8GFNUp17I7S/P4X785L6exkdparBIVShfWQVt/QmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-27T11:03:53Z"
    mac: ENC[AES256_GCM,data:FdCHDBsHpMg3WEdShpUVR6uRVdT6Tto6/paxG0vJoH3tVa5YE7/ITjIgCUveoDBuSg9sboFWnqg3T65VFwYzLoRqPcKvvCq2STWr6eenEMIdG2BKa8tiW4dPisfOuI1C4C2n40IzWLpvWV/RFicCkdPsK5MK0yta7iHZ/eymApo=,iv:fSIB8IcjoC9Bui2nF3ZOxOkTi45FryuOdhD1xk8qsro=,tag:hjbSsm+Lkap8LkDwgQ7PDQ==,type:str]
    pgp: []
    encrypted_regex: ^(.*PrivateKey.*|.*certificate.*|.*key.*|.*users.*)$
    version: 3.7.3
